const fs = require("fs");
const path = require("path");

const rootPath = path.join(__dirname, "..");
const sourcePath = path.join(rootPath, "index.html");
const outputPath = path.join(rootPath, "multi_clock_offline.html");
const translationsPath = path.join(__dirname, "translations.generated.js");

let html = fs.readFileSync(sourcePath, "utf8");
const translations = fs.readFileSync(translationsPath, "utf8").trim();
const translationTag = '<script src="resources/translations.generated.js"></script>';

if (!html.includes(translationTag)) {
    throw new Error("The translations script tag was not found in index.html.");
}

html = html.replace(
    translationTag,
    "<script>\n        " + translations.replaceAll("\n", "\n        ") + "\n    </script>"
);

const logoPaths = [...new Set(
    [...html.matchAll(/atholyLoga\/[^"']+_ctverec\.svg/g)].map((match) => match[0])
)];

if (logoPaths.length !== 8) {
    throw new Error(`Expected 8 square atoll logos, found ${logoPaths.length}.`);
}

logoPaths.forEach((logoPath) => {
    const absoluteLogoPath = path.join(rootPath, ...logoPath.split("/"));
    const logoData = fs.readFileSync(absoluteLogoPath);
    const dataUrl = "data:image/svg+xml;base64," + logoData.toString("base64");
    html = html.replaceAll(logoPath, dataUrl);
});

html = html.replace(
    "<!DOCTYPE html>",
    "<!DOCTYPE html>\n<!-- Generated by resources/build-offline.js. Edit index.html, not this file. -->"
);

fs.writeFileSync(outputPath, html, "utf8");
console.log(`Offline HTML created: ${outputPath}`);
